### ISSUE TITLE
Support non-R4 Dependencies

### ISSUE THREAD

**Issue by ngfreiter** [FSHSchool/FSHOnline#23]
There is some interest in having dependencies that are not just FHIR R4 (US Core for example): https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/FSH.20Online/near/210070678. We would need to add some way for the user to indicate the dependencies they want to load, and most of the code to actually load those dependencies should already exist.

**Comment by cmoesel** [comment]
This is done and live!
