### ISSUE TITLE
Support for re-sizable panels

### ISSUE THREAD

**Issue by mgramigna** [FSHSchool/FSHOnline#53]
Not sure if this is a desired feature, but it might be nice to be able to resize the FSH/FHIR panels in order to show more information on either end.

Someone using the site during a presentation had a tough time showing a long line while still being able to see the rest of the FSH content (i.e. without horizontal scrolling)

**Comment by cmoesel** [comment]
Sorry for the late response.  This was, in fact, already on our backlog and we hope to address it soon!
