### ISSUE TITLE
Bugs in text highlighting

### ISSUE THREAD

**Issue by markkramerus** [FSHSchool/FSHOnline#54]
There are some anomalies in the text highlighting. See attached. 
![image](https://user-images.githubusercontent.com/492232/120003696-fcfdd480-bfa3-11eb-9654-77fe0078cc87.png)

**Comment by markkramerus** [comment]
The "or" in discriminator should not be blue, the ".system" should be white, and perhaps the + in [+] should be blue.

**Comment by markkramerus** [comment]
![image](https://user-images.githubusercontent.com/492232/120007149-94b0f200-bfa7-11eb-96b6-110ff305b90d.png)

The quoted codes are not highlighted correctly in this one.

**Comment by cmoesel** [comment]
Thanks for reporting this.  We already have an open item in our backlog to fix highlighting bugs, so I've updated it to reference this issue.

**Comment by jafeltra** [comment]
The "+" and quoted codes are properly highlighted now. They were fixed as part of #56.

The erroneous highlighting of "or" in discriminator and "system" as part of a path are symptoms of shortcomings in the way we implement the syntax highlighting. We have an open issue to evaluate a different approach to try to resolve these issues.

**Comment by jafeltra** [comment]
I believe all the bugs in highlighting that are identified in this issue have been resolved and deployed to the site.
